# Generated by Django 2.0.6 on 2018-06-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20180625_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
